server:
 port: 3344

spring: 
 application:
  name: microservicecloud-config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/passion11/springcloudconfig ##github上自己的microservicecloud-config仓库地址