server:
 port: 7002
eureka:
 instance:
  hostname: eureka2.com
 client:
  registerWithEureka: false
  fetchRegistry: false 
  serviceUrl:
   defaultZone: http://eureka1.com:7001/eureka/,http://eureka3.com:7003/eureka/
  