server:
 port: 7001
eureka:
 instance:
  hostname: eureka1.com
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  