server:
 port: 7003
eureka:
 instance:
  hostname: eureka3.com
 client:
  registerWithEureka: false
  fetchRegistry: false 
  serviceUrl:
   defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
   